FROM apache/airflow:2.6.3-python3.10


ENV PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.4.2

WORKDIR /opt/airflow

COPY requirements.txt .

RUN pip install -r requirements.txt

# RUN pip install "poetry==$POETRY_VERSION"

# COPY poetry.lock pyproject.toml ./

# RUN poetry install --only main --no-interaction  --no-root